accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('dashboard', views.dashboard, name="dashboard"),
    path('profile/<int:user_id>', views.profile, name="profile"),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('new', views.post_job, name="post_job"),
    path('jobs/<int:job_id>', views.job_detail, name="job_detail"),
    path('', views.home, name="home"),
    path('jobs/<int:job_id>/bid', views.bid, name="bid"),
    path('message/<int:job_id>', views.message, name="message"),
    path('login', views.login, name="login"),
    path('bids/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
    path('register/', views.register, name="register"),
    path('post_job', views.post_job, name="post_job"),
    path('list_jobs', views.list_jobs, name="list_jobs"),
    path('complete_job/<int:job_id>', views.complete_job, name="complete_job"),
    path('complete_job/<int:job_id>/submit_translation', views.submit_translation, name="submit_translation"),
    path('translated_job/<int:job_id>', views.translated_job, name="translated_job"),
    path('dispute/<int:job_id>', views.dispute, name="dispute"),
    path('dispute/<int:job_id>/raise_dispute', views.raise_dispute, name="raise_dispute"),
    path('review/<int:job_id>', views.review, name="review"),
    path('review/<int:job_id>/post_review', views.post_review, name="post_review"),
]

translateapp/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

# Create your models here.


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    balance = models.DecimalField(max_digits=8, decimal_places=2)
    translator = models.BooleanField()

    def __str__(self):
        return f"{self.id} - {self.name}"
    
    def get_average_rating(self):
        ratings = Rating.objects.filter(rated=self.user)
        average_rating = ratings.aggregate(Avg('rating'))['rating__avg']
        return round(average_rating, 2) if average_rating else 0


class Job(models.Model):
    class Status(models.TextChoices):
        AVAILABLE = 'available', "Available"
        ASSIGNED = 'assigned', "Assigned"
        IN_PROGRESS = 'in_progress', "In Progress"
        COMPLETED = 'completed', "Completed"

    class Field(models.TextChoices):
        ART = 'art', "Art"
        BUS = 'business', "Business"
        COMP = 'computers', "Computers"
        EDU = 'education', "Education"
        ENG = 'engineering', "Engineering"
        FIN = 'finance', "Finance"
        LAW = 'law', "Law"
        LIT = 'literature', "Literature"
        MED = 'medicine', "Medicine"
        SCI = 'science', "Science"
        SOC = 'social_sciences', "Social Sciences"
        TECH = 'technology', "Technology"

    class Language(models.TextChoices):
        ENG = 'en', "English"
        SPA = 'spa', "Spanish"
        FRE = 'fr', "French"
        GER = 'de', "German"
        ITA = 'it', "Italian"
        JPN = 'ja', "Japanese"
        CRO = 'hr', "Croatian"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    source_lang = models.CharField(
        max_length=3,
        choices=Language.choices,
        default=Language.ENG,
    )
    target_lang = models.CharField(
        max_length=3,
        choices=Language.choices,
        default=Language.CRO,
    )
    field = models.CharField(
        max_length=100,
        choices=Field.choices,
        default=Field.ENG,
    )
    budget = models.DecimalField(max_digits=8, decimal_places=2)
    text = models.TextField()
    status = models.CharField(
        max_length=100,
        choices=Status.choices,
        default=Status.AVAILABLE,
    )
    translation = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.account.name} - {self.title}"

    def accepted_bid(self):
        return self.bid_set.filter(accepted=True).first()

    def accepted_bidder(self):
        return self.accepted_bid().bidder.account
    
    def accepted_bidder_user(self):
        return self.accepted_bid().bidder

    def owner(self):
        return self.user.account

    # Helper method to check if the job is available, since checking the status
    # directly from the template is not very readable.
    def is_available(self):
        return self.status == self.Status.AVAILABLE

    def is_completed(self):
        return self.status == self.Status.COMPLETED
    
    def accept_bid(self, bid):
        bid.accepted = True
        bid.save()
        self.status = self.Status.ASSIGNED
        self.save()

    def has_open_dispute(self):
        return self.dispute_set.filter(status='open').exists()
    
    def has_closed_dispute(self):
        return self.dispute_set.filter(status='closed').exists()

    @classmethod
    def accepted_jobs_for(cls, user):
        # Svi bidovi gdje je user napravio job na koji je biddano
        accepted_bids = Bid.objects.filter(job__in=user.job_set.all(), accepted=True)
        # Svi jobovi gdje je user napravio job i bidano je na job 
        accepted_jobs = [ bid.job for bid in accepted_bids if bid.job.status != "completed" ]
        return accepted_jobs


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    accepted = models.BooleanField()

    def __str__(self):
        return f"{self.bidder.account.name} - {self.job.title} - {self.price}"
    def job_owner(self):
        return self.job.user


class Dispute(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    reason = models.TextField()

    class Status(models.TextChoices):
        OPEN = 'open', "Open"
        CLOSED = 'closed', "Closed"

    status = models.CharField(
        max_length=100,
        choices=Status.choices,
        default=Status.OPEN,
    )

    def __str__(self):
        return f"{self.job.user.account.name} - {self.job.title} - dispute"


class Message(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sender")
    reciever = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="reciever")
    text = models.TextField()
    sent_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender.account.name} - {self.reciever.account.name} - {self.text[:20]}"


class Rating(models.Model):
    rater = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="rater")
    rated = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="rated")
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    rating = models.IntegerField()

    def __str__(self):
        return f"{self.job.user.account.name} - {self.job.title} - rating - {self.rating}"

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from app.models import Account, Job, Bid, Dispute, Message, Rating
from django.db.models import Avg


@login_required
def dashboard(request):
    user = request.user
    my_jobs = user.job_set.all()
    my_messages = Message.objects.filter(
        reciever=user) | Message.objects.filter(sender=user)
    my_messages = my_messages.order_by("sent_at")
    context = {
        'my_jobs': my_jobs,
        'my_messages': my_messages,
    }
    return render(request, 'accounts/dashboard.html', context)


def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    completed_jobs = Job.objects.filter(user=user, status="completed")
    accepted_jobs = Job.accepted_jobs_for(user)

    bids = user.bid_set.all()
    won = user.bid_set.filter(accepted=True)

    context = {
        'profile_user': user,
        'accepted_jobs': accepted_jobs,
        'completed_jobs': completed_jobs,
        'bids': bids,
        'won': won,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/dashboard.html
{% extends 'app/base.html' %}

{% block content %}

<div class='container'>
    <div class='row'>
        <div class='col-md-9'>
            <div class="account-info">
                <h1>Hello <mark class="purple">{{ user.account.name }}</mark> </h1>
                <p>Token balance: <strong>{{ user.account.balance }}</strong></p>
                <p>Email: <strong>{{ user.email }}</strong></p>
            </div>

            <h1>My jobs</h1>

            {% for job in my_jobs %}
            <div class="job">
                <h3 style="color:#1de9b6">{{ job.title }}</h3>
                <p>

                    <strong>Job description: </strong>{{ job.description }}
                    <br>
                    <strong>Source language:</strong> {{ job.source_lang }}
                    <br>
                    <strong>Target language:</strong> {{ job.target_lang }}
                </p>
                <strong>Job field: </strong>{{ job.field }}
                <br>
                <strong>Job budget: </strong>{{ job.budget }}
                <br>
                <strong>Job status: </strong>{{ job.status }}

                <div>
                    {% for bid in job.bid_set.all %}
                    <div class='bid'>
                        <h2>
                            <a href="{% url 'accounts:profile' bid.bidder.id %}">
                                Bidder: {{ bid.bidder.account.name }}
                            </a>
                        </h2>
                        <strong>Price: </strong> {{ bid.price }}
                        <p><strong>Bid status: </strong>{% if bid.accepted %}
                            Accepted.
                            {% elif not bid.accepted and job.is_available %}
                            <!--check models.py for the is_available method-->
                            Not accepted.
                        <p>
                        <form action="{% url 'app:accept_bid' bid.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-primary d-inline-flex flex-row align-items-center" type="submit"
                                value="Accept bid">
                        </form>
                        </p>
                        {% endif %}
                        </p>
                    </div>
                    {% empty %}
                    <br>
                    <p style="color:#1de9b6">No bids on this job yet.</p>
                    {% endfor %}
                </div>
                {% if job.status == 'completed' %}
                <div class="translation_options">
                    <button class="btn btn-primary d-inline-flex flex-row align-items-center">
                        <a href="{% url 'app:translated_job' job.id%}">View translation</a>
                    </button>
                    {% if job.rating %}
                    <button class="btn btn-primary d-inline-flex flex-row align-items-center">
                        <a href="{% url 'app:review' job.id %}">Review the translation</a>
                    </button>
                    {% else %}
                    {% endif %}
                </div>
                {% endif %}
            </div>
            {% endfor %}

        </div>

        <div class="col-md-3">
            <h1>Messages</h1>
            <div class="messages">
                {% for message in my_messages %}
                <div class="message {% if user == message.sender %} my_message {% else %} their_message {% endif %}">
                    {% if user != message.sender %}
                    <strong>From:
                        <a href="{% url 'accounts:profile' message.sender.id %}">
                            {{ message.sender.account.name }}
                        </a>
                    </strong>
                    {% endif %}
                    <small>{{ message.sent_at }}</small>
                    <p>{{ message.text }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'app/base.html' %}

{% block content %}

<div class='container'>
    <div class='row'>
        <div class='col-md-12'>
            <h1>{{ profile_user.account.name }}</h1>
            <p>Email: <strong>{{ user.email }}</strong></p>
            <p>Average rating: {{ user.account.get_average_rating }}</p>
        </div>
    </div>
    <h2 style="text-align:center;">Job informations</h2>
    <div class='row'>
        <div class="col-md-12">
            <h1 style="color:#443a84">Accepted jobs</mark></h1>

            {% for job in accepted_jobs %}
            <div class="job">
                <h3 style="color:#1de9b6">{{ job.title }}</h3>
                <p>

                    <strong>Job description: </strong>{{ job.description }}
                    <br>
                    <strong>Source language:</strong> {{ job.source_lang }}
                    <br>
                    <strong>Target language:</strong> {{ job.target_lang }}
                </p>
                <strong>Job field: </strong>{{ job.field }}
                <br>
                <strong>Job budget: </strong>{{ job.budget }}
                <br>
                <strong>Job status: </strong>{{ job.status }}
                <p>
                    <br>
                    <strong>
                        {{ job.accepted_bidder.name }} was accepted for this job wit the bid
                        of {{ job.accepted_bid.price }}
                    </strong>
                </p>
            </div>
            {% empty %}
            <p>No accepted jobs</p>
            {% endfor %}

        </div>

        <div class="col-md-12">

            <h1 style="color:#443a84">Completed jobs</mark></h1>

            {% for job in completed_jobs %}
            <div class="job">
                <h3>{{ job.title }}</h3>
                <p>
                    <strong>{{ job.description }}</strong> <br>
                    Source language: {{ job.source_lang }}
                    Target language: {{ job.target_lang }}
                </p>
                <p>{{ job.field }}</p>
                <p>{{ job.budget }}</p>
                <p>{{ job.status }}</p>

                <p>
                    <strong>
                        {{ job.accepted_bidder.name }} has completed this job for the price
                        of {{ job.accepted_bid.price }}
                    </strong>
                </p>

                {% if user == job.user %}
                {% if job.has_open_dispute %}
                <p>This job has an open dispute on it.</p>
                {% elif job.has_closed_dispute %}
                <p>This dispute has been resloved and closed.</p>
                {% else %}
                <p>
                    <button class="btn btn-primary d-inline-flex flex-row align-items-center">
                        <a href="{% url 'app:dispute' job.id %}">Raise a dispute</a>
                    </button>
                </p>
                {% endif %}
                {% endif %}
            </div>
            {% empty %}
            <p>No completed jobs</p>
            {% endfor %}
        </div>

        {% if user.account.translator %}
        <div class="col-md-12">
            <h2 style="text-align:center;">Translator informations</h2>
            <h1 style="color:#443a84">User's bids</h1>
            {% for bid in bids %}
            <div class="job">
                <h4>Bid on {{ bid.job.title }} for {{ bid.price }} tokens</h4>
                {% if bid.accepted %}
                <p>You have won the job!</p>
                {% else %}
                <p>Other translator has won the job.</p>
                {% endif %}
            </div>
            {% empty %}
            <p>No bids on any jobs</p>
            {% endfor %}
        </div>

        <div class="col-md-12">
            <h1 style="color:#443a84">Currently working on</h1>
            {% for bid in won %}

            <div class="job">
                <h4>{{ bid.job.title }} for {{ bid.price }} tokens</h4>
                <p>Translating from:
                    {{ bid.job.get_source_lang_display }} to
                    {{ bid.job.get_target_lang_display }} in the field of
                    {{ bid.job.field }} .
                </p>
                <p>Job was posted by <a href="{% url 'accounts:profile' bid.job.user.id %}">
                        {{ bid.job.user.account.name }}</a></p>
                {% if not bid.job.translation and user == bid.bidder %}
                <button class="btn btn-primary d-inline-flex flex-row align-items-center">
                    <a href="{% url 'app:complete_job' bid.job.id %}">Submit translation</a>
                </button>
                {% endif %}
            </div>
            {% empty %}
            <p>This user did not win any bids.</p>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}