accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('dashboard', views.dashboard, name="dashboard"),
    path('profile/<int:user_id>', views.profile, name="profile"),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('new', views.post_job, name="post_job"),
    path('jobs/<int:job_id>', views.job_detail, name="job_detail"),
    path('', views.home, name="home"),
    path('jobs/<int:job_id>/bid', views.bid, name="bid"),
    path('message/<int:job_id>', views.message, name="message"),
    path('login', views.login, name="login"),
    path('bids/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
    path('register/', views.register, name="register"),
    path('post_job', views.post_job, name="post_job"),
    path('list_jobs', views.list_jobs, name="list_jobs"),
    path('complete_job/<int:job_id>', views.complete_job, name="complete_job"),
    path('complete_job/<int:job_id>/submit_translation', views.submit_translation, name="submit_translation"),
    path('translated_job/<int:job_id>', views.translated_job, name="translated_job"),
    path('dispute/<int:job_id>', views.dispute, name="dispute"),
    path('dispute/<int:job_id>/raise_dispute', views.raise_dispute, name="raise_dispute"),
    path('review/<int:job_id>', views.review, name="review"),
    path('review/<int:job_id>/post_review', views.post_review, name="post_review"),
]

translateapp/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

app/templates/app/base.html
{% load static %}
<html>

<head>
  <title>Translate-o-rama</title>
  <!--font-->
  <link href="https://rsms.me/inter/inter-ui.css" rel="stylesheet">

  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
    integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

  <link rel="stylesheet" href="{% static 'app/css/default.css' %}">
</head>

<body>
  <div class="page-header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Translate-o-rama</a>
      {% if user.is_authenticated %}
      <div class="post_job">
        <a href="{% url 'app:post_job' %}">Post a new job</a>
      </div>
      <div class="browse_jobs">
        <a href="{% url 'app:list_jobs' %}">Browse jobs</a>
      </div>
      {% endif %}

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-link" href="{% url 'accounts:profile' user.id %}">My profile</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts:dashboard' %}">{{ user.account.name }}</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% elif request.resolver_match.view_name == 'login' %}
          <li class="nav-item active">
            <a class="nav-link-features page-scroll" href="{% url 'app:register' %}">Register</a>
          </li>
          {% elif request.resolver_match.view_name == 'app:register' %}
          <li class="nav-item active">
            <a class="nav-link-features page-scroll" href="{% url 'login' %}">Login</a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link-features page-scroll" href="#features">Features</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>

  <div class="content container">
    <div class="row">
      <div class="col-md-12">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
  <script src="{% static 'app/javascript/scripts.js' %}"></script>
</body>

<br>
</html>

app/templates/app/complete_job.html
{% extends 'app/base.html' %}

{% block content %}

<div class="text_to_translate">
    <h3 style="color:#443a84">Text to be translated.</h3>
    <p>{{ job.text }}</p>
</div>

<div class="translate_text_given">
    <h3 style="color:#1de9b6">Submit translation.</h3>
    <form method="post" action="{% url 'app:submit_translation' job_id=job.id %}">
        {% csrf_token %}
        <p class="text_box">
            <textarea name="text" rows="15" cols="50" style="resize: none;"></textarea>
        </p>
        
        <p>
            <br>
            <input class="btn btn-primary d-inline-flex flex-row align-items-center" type="submit" value="Submit translation">
        </p>
    </form>

</div>

{% endblock content %}

app/templates/app/detail.html
{% extends 'app/base.html' %}
{% block content %}

<div class"container">
    <div class="row">
        <div class="col-md-6">
            <h1>{{ image.title }}</h1>
            <div>
                <p>Objavljeno: {{ image.pub_date }}</p>
                <p>Objavilo: {{ image.user.username }}</p>
                <img src="{{ image.url }}" class="full-width">

                {% if user.is_superuser %}
                    <form action="{% url 'app:delete_image' image.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete" style="float: right;"/>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <h1>Komentari</h1> 
            {% for comment in comments %}
                {% if comment.approved or user.is_superuser or user == comment.user %}
                    <p class="comment">
                        <strong>{{ comment.user.username }}</strong>
                        ( {{ comment.pub_date }} ) 
                        {% if not comment.approved %}- unapproved {% endif %}<br/>
                        {{ comment.text }}
                        {% if not comment.approved and user.is_superuser %}
                            <br>
                            <span class="red" style="color: red">
                                <form action="{% url 'app:approve_comment' comment.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Approve" >
                                </form>
                            </span>
                        {% endif %}
                </p>
                {% endif %}
            {% endfor %}
            <form action="{% url 'app:post_comment' image.id %}" method="post">
                {% csrf_token %}
                <p>
                    <label for="comment_text">Text</label>
                    <input id="comment_text" name="text" type="text">
                </p>

                <input type="submit">
            </form>
        </div>     
    </div>
</div>

{% endblock %}

app/templates/app/dispute.html
{% extends 'app/base.html' %}

{% block content %}

<div class="left_dispute">
    <div class="left_dispute_style">
        <h2>Job title: {{ job.title }}</h2>
        <h3>Job posted by: {{ job.user.account.name }}</h3>
        <h3>Job translated by: {{ job.accepted_bidder.name }}</h3>
        <br>
        <p>Job description: {{ job.description }}</p>
        <p>Source language: {{ job.source_lang }}</p>
        <p>Target language: {{ job.target_lang }}</p>
        <p>Field: {{ job.field }}</p>
        <br>

        <p>Text:</p>
        <p>{{ job.text }}</p>
        <p>Translation:</p>
        <p>{{ job.translation }}</p>
    </div>
</div>

<div class="right_dispute">
    <form method="post" action="{% url 'app:raise_dispute' job.id %}">
        {% csrf_token %}
        <label>Reason for the dispute</label>
        <p class="text_box">
            <textarea name="text" rows="15" cols="50" style="resize: none;"></textarea>
        </p>

        <p>
            <br>
            <input class="btn btn-primary d-inline-flex flex-row align-items-center" type="submit"
                value="Raise dispute">
        </p>
    </form>
</div>

{% endblock content %}

app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}

<!--navigation-->
<section class="smart-scroll">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#features">Features</a>
                </li>
            </ul>
        </div>
        </nav>
    </div>
</section>

<!--hero header-->
<section class="py-7 py-md-0 bg-hero" id="home">
    <div class="container">
        <div class="row vh-md-100">
            <div class="col-md-8 col-sm-10 col-12 mx-auto my-auto text-center">
                <h1 class="heading-black text-capitalize">Translate everything you need with Translate-o-Rama</h1>
                <p class="lead py-3">Translate-o-Rama is a platform that provides multiple translate services used in everywhere.</p>
                <button class="btn btn-primary d-inline-flex flex-row align-items-center">
                    <a href="{% url 'login' %}">Login</a>
                </button>
                <button style="margin-left:50px;" class="btn btn-primary d-inline-flex flex-row align-items-center">
                    <a href="{% url 'app:register' %}">Register</a>
                </button>
            </div>
        </div>
    </div>
</section>

<!-- features section -->
<section class="pt-6 pb-7" id="features">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2 class="heading-black">Employ or be employed</h2>
                <p class="text-muted lead">At our website you can choose to be an employer, or post a job with description visible to all of our checked translators.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <div class="row feature-boxes">
                    <div class="col-md-6 box">
                        <div class="icon-box box-primary">
                            <div class="icon-box-inner">
                                <span data-feather="edit-3" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Post a job. Describe it.</h5>
                        <p class="text-muted">Finding and employee has never been easier using the service we provide.</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-success">
                            <div class="icon-box-inner">
                                <span data-feather="monitor" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Work and earn from home.</h5>
                        <p class="text-muted">Feel free to show your creative side and represent yourself in the best way and win all the bids!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--scroll to top-->
<div class="scroll-top">
    <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>
{% endblock content %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}
        <p>
            <a href="{% url 'home_path' %}">HOME</a>
        </p>
        <h1>Sve slike</h1>
        <p>Dobrodošli na naš imgur</p>
        {% for image in image_list %}
            <div>
                <p>Naziv: 
                    <a href="{% url 'app:detail' image.id %}">
                        {{ image.title }}
                    </a>
                </p>
                <p>Objavljeno: {{ image.pub_date }}</p>
                <img src="{{ image.url }}" style="width:300px;">
            </div>
        {% endfor %}
{% endblock content %}

app/templates/app/jobs_detail.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="job-detail-title" style="color:white";>Job details</h1>
<hr>
<h2 class="job-detail-title">Job title: {{ job.title }}</h1>
<div class="job">
    <p>
        <strong>Job description: </strong>{{ job.description }}
        <br>
        <strong>Source language:</strong> {{ job.source_lang }}
        <br>
        <strong>Target language:</strong> {{ job.target_lang }}
    </p>

    <strong>Job field: </strong>{{ job.field }}
    <br>
    <strong>Job budget: </strong>{{ job.budget }}
    <br>
    <strong>Job status: </strong>{{ job.status }}
    <br>
    <strong>Job owner: </strong>{{ job.owner.name}}
</div>
<div class="col-md-4">
    <h2>Enter your bid:</h2>
    <form action="{% url 'app:bid' job.id %}" method="post" >
      {% csrf_token %}
      <div class="form-group">
        <label for="price">Bid</label>
        <input type="number" class="form-control" id="price" name="price" placeholder="Enter bid">
        {% for error in form.price.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      
    </form>
  </div>

{% endblock %}

app/templates/app/list_jobs.html
{% extends 'app/base.html' %}

{% block content %}

{% for job in job_list %}
<div class="job">
    <h3 style="color:#1de9b6">{{ job.title }}</h3>
    <p>

        <strong>Job description: </strong>{{ job.description }}
        <br>
        <strong>Source language:</strong> {{ job.source_lang }}
        <br>
        <strong>Target language:</strong> {{ job.target_lang }}
    </p>
    <strong>Job field: </strong>{{ job.field }}
    <br>
    <strong>Job budget: </strong>{{ job.budget }}
    <br>
    <strong>Job status: </strong>{{ job.status }}
    <br>
    <br>
    <strong>Posted by: </strong> <a href="{% url 'accounts:profile' job.user.id %}">{{ job.user.account.name }}</a>

    <div>
        {% for bid in job.bid_set.all %}
        <div class='bid'>
            <h2>
                <a href="{% url 'accounts:profile' bid.bidder.id %}">
                    Bidder: {{ bid.bidder.account.name }}
                </a>
            </h2>
            <strong>Price: </strong> {{ bid.price }}
            <p><strong>Bid status: </strong>{% if bid.accepted %}
                Accepted.
                {% else %}
                Not accepted.
                {% endif %}
            </p>
        </div>
        {% empty %}
        <br>
        <p style="color:#1de9b6">No bids on this job yet.</p>
        {% endfor %}
    </div>
</div>
<div>
    {% if not job.id in bidded_job_ids and not job.status.AVAILABLE %}
    <div class="bid_button">
        <button class="btn btn-primary d-inline-flex flex-row align-items-center">
            <a href="{% url 'app:job_detail' job.id %}">Bid on a job</a>
        </button>
    </div>
    {% endif %}
    <div class="message_button">
        <button class="btn btn-primary d-inline-flex flex-row align-items-center">
            <a href="{% url 'app:message' job.id %}">Message user</a>
        </button>
    </div>
    <br>
</div>
{% endfor %}
{% endblock %}

app/templates/app/message.html
{% extends 'app/base.html' %}

{% block content %}
<div class="container">
    <div class="job">
        <h2>Send a message to {{ job.user.account.name }}</h2>
        <form method="post">
            {% csrf_token %}
            <p>
                <label>Message</label>
                <br>
                <input type="text" name="message_send" />
            </p>

            <p>
                <input class="btn btn-primary" type="submit" value="Send message" />
            </p>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/app/post_job.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="posta_job">Post a new job</h1>
<hr>
<br>
<form method="post">
    {% csrf_token %}
    <div class="container">
        <div class="info_job">
            <p>
                <label>Title</label>
                <br>
                <input type="text" name="title" />
            </p>

            <p>
                <label>Description</label>
                <br>
                <input type="text" name="description" />
            </p>

            <p>
                <label>Source language</label>
                <br>
                <select name="source_lang">
                    <option value="en">English</option>
                    <option value="spa">Spanish</option>
                    <option value="fr">French</option>
                    <option value="de">German</option>
                    <option value="it">Italian</option>
                    <option value="ja">Japanese</option>
                    <option value="hr">Croatian</option>
                </select>
            </p>

            <p>
                <label>Target language</label>
                <br>
                <select name="target_lang">
                    <option value="en">English</option>
                    <option value="spa">Spanish</option>
                    <option value="fr">French</option>
                    <option value="de">German</option>
                    <option value="it">Italian</option>
                    <option value="ja">Japanese</option>
                    <option value="hr">Croatian</option>
                </select>
            </p>

            <p>
                <label>Field</label>
                <br>
                <select name="field">
                    <option value="art">Art</option>
                    <option value="business">Business</option>
                    <option value="computers">Computers</option>
                    <option value="education">Education</option>
                    <option value="engineering">Engineering</option>
                    <option value="finance">Finance</option>
                    <option value="law">Law</option>
                    <option value="literature">Literature</option>
                    <option value="medicine">Medicine</option>
                    <option value="science">Science</option>
                    <option value="social_sciences">Social Sciences</option>
                    <option value="technology">Technology</option>
                </select>
            </p>

            <p>
                <label>Budget</label>
                <br>
                <input type="text" name="budget" />
            </p>

            <p>
                <br>
                <input class="btn btn-primary" type="submit" value="Post job" />
            </p>
        </div>

        <div class="text_translate">
            <p class="text_box">
                <label>Text to translate</label>
                <br>
                <textarea name="text" rows="15" cols="50" style="resize: none;"></textarea>
            </p>

        </div>
    </div>
</form>
{% endblock %}

app/templates/app/review.html
{% extends 'app/base.html' %}

{% block content %}

<div class="left_review">
    <div class="left_review_style">
        <h2>Job title: {{ job.title }}</h2>
        <h3>Job posted by: {{ job.user.account.name }}</h3>
        <h3>Job translated by: {{ job.accepted_bidder.name }}</h3>
        <br>
        <p>Job description: {{ job.description }}</p>
        <p>Source language: {{ job.source_lang }}</p>
        <p>Target language: {{ job.target_lang }}</p>
        <p>Field: {{ job.field }}</p>
        <br>

        <p>Text:</p>
        <p>{{ job.text }}</p>
        <p>Translation:</p>
        <p>{{ job.translation }}</p>
    </div>
</div>

<div class="right_review">
    <form method="post" action="{% url 'app:post_review' job.id %}">
        {% csrf_token %}
        <label>Rate the translation</label>
        <br>
        {% for i in "12345" %}
        <span class="fa fa-star" id="{{ i }}" onclick="setRating('{{ i }}')"></span>
        {% endfor %}

        <input type="hidden" name="rating" id="rating" value="">
        <p>
            <br>
            <input class="btn btn-primary d-inline-flex flex-row align-items-center" type="submit"
                value="Submit rating">
        </p>
    </form>
</div>


<script>
    var rating = 0;
    function setRating(newRating) {
        if (rating == newRating) {
            // If the same rating is clicked again, deselect it
            rating = 0;
        } else {
            // Otherwise, set the new rating
            rating = newRating;
        }
        document.getElementById("rating").value = rating;
        for (var i = 1; i <= 5; i++) {
            var star = document.getElementById(i);
            if (i <= rating) {
                // Fill the star if the rating is up to this star
                star.classList.add("checked");
            } else {
                // Otherwise, unfill the star
                star.classList.remove("checked");
            }
        }
    }
</script>

{% endblock content %}

app/templates/app/translated_job.html
{% extends 'app/base.html' %}

{% block content %}

<div class="translated_text">
    <h2 style="color:#00acbf">Text translated by {{ bid.bidder.account.name }}</h2>
    <br>
    <div class="job_translation">
        <p>{{ job.translation }}</p>
    </div>
</div>

{% endblock content %}